name:        hdiff
version:     0.0.0
synopsis:    Hash Diff returning a Pattern-Expression-based result instead of Edit-Script
description: see README or paper.
maintainer:  Victor Miraldo <v.cacciarimiraldo@gmail.com>
github:      VictorCMiraldo/hdiff
category:    Other

dependencies:
  - base >= 4.9 && < 5
  - generics-mrsop >= 2.1.0
  - generics-mrsop-gdiff
  - bytestring
  - cryptonite
  - containers
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - QuickCheck
  - hspec
  - memory

library:
  source-dirs: src/
  ghc-options: -Wall

tests:
  spec: 
    main: Spec.hs
    source-dirs: 
      - tests
    dependencies:
      - hdiff

executables:
  hdiff:
    source-dirs:
      - executables
    main: HDiff.hs
    dependencies:
      - parsec
      - gitrev
      - optparse-applicative
      - language-lua
      - hs-elisp
      - hdiff
    ghc-options: -Wno-overlapping-patterns -Wno-inaccessible-code -Wno-incomplete-patterns -Wno-incomplete-uni-patterns -Wno-incomplete-record-updates 


