name:        hdiff
version:     0.0.5
synopsis:    Pattern-Expression-based differencing of arbitrary types.
description: This package provides an executable and a library to compute
             and manipulate pattern-expression based differences between
             values of arbitrary datatypes. For more detailed information
             check the README at our GitHub page.
maintainer:  Victor Miraldo <v.cacciarimiraldo@gmail.com>
github:      VictorCMiraldo/hdiff
category:    Other

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - cryptonite
  - containers
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - QuickCheck
  - hspec
  - memory
  - template-haskell
  - deepseq
  - simplistic-generics

library:
  source-dirs: src/
  ghc-options: -O2 -Wall

tests:
  spec: 
    main: Spec.hs
    source-dirs: 
      - tests
    dependencies:
      - hdiff

executables:
  hdiff:
    source-dirs:
      - executable
    main: HDiff.hs
    dependencies:
      - parsec
      - gitrev
      - optparse-applicative
      - language-lua
      - language-java
      - language-ecmascript
      - language-bash
      - language-python
      - time
      - deepseq
      - hdiff
    cpp-options: -DREAL_LANGUAGES
    ghc-options: -XCPP -O2 -Wno-overlapping-patterns -Wno-inaccessible-code -Wno-incomplete-patterns -Wno-incomplete-uni-patterns -Wno-incomplete-record-updates 
