name:        hdiff
version:     0.0.3
synopsis:    Pattern-Expression-based differencing of arbitrary types.
description: This package provides an executable and a library to compute
             and manipulate pattern-expression based differences between
             values of arbitrary datatypes. For more detailed information
             check the README at our GitHub page.
maintainer:  Victor Miraldo <v.cacciarimiraldo@gmail.com>
github:      VictorCMiraldo/hdiff
category:    Other

dependencies:
  - base >= 4.9 && < 5
  - bytestring
  - cryptonite
  - containers
  - mtl
  - prettyprinter
  - prettyprinter-ansi-terminal
  - text
  - QuickCheck
  - hspec
  - memory
  - template-haskell

library:
  source-dirs: src/
  ghc-options: -Wall

tests:
  spec: 
    main: Spec.hs
    source-dirs: 
      - tests
    dependencies:
      - hdiff

executables:
  #  Here's the STDiff executable we need to run the tests
  #  with stdiff
  #
  #  stdiff:
  #    source-dirs:
  #      - executables/stdiff
  #    main: STDiff.hs
  #    dependencies:
  #      - generics-mrsop
  #      - generics-mrsop-gdiff
  #      - parsec
  #      - gitrev
  #      - optparse-applicative
  #      - language-lua
  #    ghc-options: -Wno-overlapping-patterns -Wno-inaccessible-code -Wno-incomplete-patterns -Wno-incomplete-uni-patterns -Wno-incomplete-record-updates 

  hdiff:
    source-dirs:
      - executables/hdiff
    main: HDiff.hs
    dependencies:
      - parsec
      - gitrev
      - optparse-applicative
      - language-lua
      - language-java
      - language-javascript
      - language-bash
      - language-python
      - hdiff
    ghc-options: -Wno-overlapping-patterns -Wno-inaccessible-code -Wno-incomplete-patterns -Wno-incomplete-uni-patterns -Wno-incomplete-record-updates 


