resolver: lts-14.1

extra-deps:
  - git: git@github.com:VictorCMiraldo/generics-mrsop.git
    commit: 293bbd43b07f6562ca72725218bb1bd8d7406767
  - git: git@github.com:arianvp/generics-mrsop-gdiff.git
    commit: 4249f5a6ecb2b03dce78118dc522412c0b545fc9
  # - generics-mrsop-2.3.0
  # - generics-mrsop-gdiff-0.0.1
  - language-lua-0.11.0.1
  - alex-tools-0.4

