# We need 12.2 because language-lua-0.11.0 requires so... 
resolver: lts-14.1

extra-deps:
  # - generics-mrsop-2.1.0
  - language-lua-0.11.0.1
  - alex-tools-0.4
  - git: git@github.com:arianvp/generics-mrsop-gdiff.git
    commit: 4c80f8c81084c46dd121106d7a83f9f11381a15a 
  - git: git@github.com:VictorCMiraldo/generics-mrsop.git
    commit: d892f9330d5e7fd6fab5fc3305bdf563bb9e6b1f
  - git: git@github.com:VictorCMiraldo/hs-elisp.git
    commit: 2aa7dbe8786a150d3bc611b86a56cdc8a16b8aa7

