
resolver: lts-12.2

packages:
  - .
  - location:
      git: git@github.com:VictorCMiraldo/generics-mrsop.git
      commit: 9cee726fef18ca7fe380409244bce0cd9ef8ade0
    extra-dep: true

extra-deps:
  - language-lua-0.11.0
  - alex-tools-0.4
#  - generics-mrsop-1.2.2@sha256:9c5a7ebbf36c82d0009cc8e66b5d780a1a908579aa00357d15dda02eb88022b9
 

