resolver: lts-14.1

extra-deps:
  - git: git@github.com:VictorCMiraldo/generics-mrsop.git
    commit: a45f12cb41f72afc6ab2ac94a09928be1c05219a
  - generics-mrsop-gdiff-0.0.2
  - language-lua-0.11.0.1
  - alex-tools-0.4

