resolver: lts-14.1

extra-deps:
  - generics-mrsop-2.2.0
  - git: git@github.com:arianvp/generics-mrsop-gdiff.git
    commit: a4ddfe477baf017480a6585db6a5b50dd134c4cc
  - language-lua-0.11.0.1
  - alex-tools-0.4

