
resolver: lts-12.2

packages:
  - .
    #- location:
    #-   git: git@github.com:VictorCMiraldo/hs-elisp.git
    #-   commit: 6b96fa2ad49777d7e3e254d35614b8b3069b35d3
    #- extra-dep: true
  - location:
      git: git@github.com:arianvp/generics-mrsop-gdiff.git
      commit: e8d2ef8db225c60693084e1b3e83fffb2514ed12
    extra-dep: true
##  - location:
##      git: git@github.com:VictorCMiraldo/generics-mrsop.git
##      commit: 9cee726fef18ca7fe380409244bce0cd9ef8ade0
##    extra-dep: true

extra-deps:
  - ../hs-elisp
  - language-lua-0.11.0
  - alex-tools-0.4
  - generics-mrsop-2.0.0
#  - generics-mrsop-1.2.2@sha256:9c5a7ebbf36c82d0009cc8e66b5d780a1a908579aa00357d15dda02eb88022b9
 

